# Site settings
title: Sebastian Neira | Portafolio
description: Portafolio de desarrollo web
baseurl: "/"
url: "http://neira9919.github.io"

# User settings
username: Sebastian Neira
user_description: Hola! Mi nombre es Sebastian Neira, técnico en informatica, Analista Programador. Ansioso por afrontar nuevos desafíos y nuevos aprendizajes. Soy un entusiasta de aprender nuevas tecnologías, que me permitan crear soluciones de calidad de forma eficiente. Programador web junior con experiencia en desarrollo web con tecnologias modernas.
user_title: Web Programmer / Desarrollador Web
email: neira9919@gamil.com
twitter_username: lorem_ipsum
github_username:  Neira9919
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
